---
# tasks file for nginx-ssl-router

- apt: name=nginx state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Gather facts
  action: ec2_facts

- name: lookup certificates
  s3: bucket="{{ ssl_router_s3_bucket }}" prefix="{{ ssl_router_s3_path }}" mode=list region={{ansible_ec2_placement_region}}
  register: ssl_domains

- debug: msg="{{ item }}"
  with_items: "{{ ssl_domains.s3_keys }}"

- name: ensure {{ ssl_router_nginx_config_dir }} exists
  file: path={{ ssl_router_nginx_config_dir }} state=directory

- name: ensure {{ ssl_router_nginx_enabled_dir }} exists
  file: path={{ ssl_router_nginx_enabled_dir }} state=directory

# s3 module failing, using shell command
- name: copy ssl certificates
  shell: aws s3 cp s3://{{ ssl_router_s3_bucket }}/{{ item }} {{ ssl_router_nginx_config_dir }}{{ item | basename }}.cert
  with_items: "{{ ssl_domains.s3_keys }}"

- name: set permissions
  file: path="{{ ssl_router_nginx_config_dir }}{{ item | basename }}.cert" mode=0400
  with_items: "{{ ssl_domains.s3_keys }}"

- name: add catch all
  template: src=templates/verygoodproxy.conf.j2 dest={{ ssl_router_nginx_config_dir }}verygoodproxy.conf mode=0400

- name: add catch all certificate
  shell: aws s3 cp s3://{{ ssl_router_s3_bucket }}/ssl.verygoodproxy.cert {{ ssl_router_nginx_config_dir }}verygoodproxy.cert

- name: activate catch all
  file: src={{ ssl_router_nginx_config_dir }}verygoodproxy.conf dest={{ ssl_router_nginx_enabled_dir }}verygoodproxy.conf state=link

- name: render config
  template: src=templates/nginx.conf.j2 dest={{ ssl_router_nginx_config_dir }}{{ item | basename }}.config mode=0400
  with_items: "{{ ssl_domains.s3_keys }}"

- name: symlink to available
  file: src={{ ssl_router_nginx_config_dir }}{{ item | basename }}.config dest={{ ssl_router_nginx_enabled_dir }}{{ item | basename }}.config state=link
  with_items: "{{ ssl_domains.s3_keys }}"

- name: reload nginx
  service: name=nginx state=reloaded
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
